export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "on-tertiary-container": "#744000",
        "surface-container-lowest": "#0d0e11",
        "secondary-fixed-dim": "#4fdbc8",
        "on-secondary": "#003731",
        "error-container": "#93000a",
        "inverse-primary": "#006b5f",
        "surface-container-high": "#292a2d",
        "surface-bright": "#38393c",
        primary: "#57f1db",
        "on-primary": "#003731",
        surface: "#121316",
        "surface-1": "#141519",
        bg: "#0d0e11",
        "surface-2": "#1a1c22",
        border: "rgba(255,255,255,0.08)",
        "border-hover": "rgba(255,255,255,0.18)",
        text: "#e8e9ec",
        muted: "#8a8d96",
        faint: "#4a4d55",
        "primary-hover": "#3cddc7",
        "risk-critical": "#ef4444",
        "risk-high": "#f97316",
        "risk-medium": "#ffb45c",
        "risk-low": "#57f1db",
        "on-surface-variant": "#bacac5",
        "on-secondary-fixed-variant": "#005048",
        "on-secondary-container": "#003f38",
        "on-tertiary-fixed": "#2d1600",
        "tertiary-fixed-dim": "#ffb875",
        "surface-container-low": "#1b1b1f",
        "secondary-fixed": "#71f8e4",
        "inverse-on-surface": "#303034",
        "on-primary-container": "#00574d",
        "surface-variant": "#343538",
        "primary-fixed": "#62fae3",
        "tertiary-container": "#ffac5a",
        "on-surface": "#e3e2e6",
        "on-error": "#690005",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#6b3b00",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005047",
        "surface-container-highest": "#343538",
        "outline-variant": "#3c4a46",
        "primary-fixed-dim": "#3cddc7",
        "tertiary-fixed": "#ffdcc0",
        "primary-container": "#2dd4bf",
        "surface-container": "#1f1f23",
        "secondary-container": "#04b4a2",
        outline: "#859490",
        tertiary: "#ffd1aa",
        secondary: "#4fdbc8",
        "surface-dim": "#121316",
        "surface-tint": "#3cddc7",
        "on-tertiary": "#4b2800",
        background: "#121316",
        "inverse-surface": "#e3e2e6",
        "on-background": "#e3e2e6",
        "on-secondary-fixed": "#00201c",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "lex-lg": "24px",
        "lex-gutter": "16px",
        "lex-md": "16px",
        "lex-unit": "4px",
        "lex-xs": "4px",
        "lex-container-margin": "32px",
        "lex-sm": "8px",
        "lex-xl": "40px",
        "lex-2xl": "80px",
        "lex-3xl": "120px",
        "lex-4xl": "160px",
      },
      fontFamily: {
        "headline-sm": ["Instrument Serif"],
        "label-md": ["Geist"],
        "body-sm": ["Geist"],
        "display-lg": ["Instrument Serif"],
        "code-sm": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "display-lg-mobile": ["Instrument Serif"],
        "headline-md": ["Instrument Serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
      },
    },
  },
};
