[phases.setup]
nixPkgs = ["bun", "openssl"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun --filter @lexguard/worker run build"]

[start]
cmd = "bun --filter @lexguard/worker run start"
