import { answerScenarioQuestion } from "@lexguard/ai";
import { chatMessages, clauses, contracts, tenantContractFilter } from "@lexguard/db";
import { and, asc, desc, eq, sql } from "drizzle-orm";
import { HTTPException } from "hono/http-exception";
import { db } from "../lib/db";
import { toPgVector } from "../lib/vector";
import type { AuthUser } from "../middleware/auth";
import { aiClient, defaultModel, recordAiUsage } from "./ai.service";

export class ChatService {
  async history(contractId: string, user: AuthUser) {
    await ensureContractAccess(contractId, user);
    return db
      .select()
      .from(chatMessages)
      .innerJoin(contracts, eq(chatMessages.contractId, contracts.id))
      .where(and(eq(chatMessages.contractId, contractId), eq(contracts.orgId, user.orgId)))
      .orderBy(asc(chatMessages.createdAt));
  }

  async clear(contractId: string, user: AuthUser) {
    await ensureContractAccess(contractId, user);
    await db
      .delete(chatMessages)
      .where(and(eq(chatMessages.contractId, contractId), eq(chatMessages.userId, user.id)));
    return { ok: true };
  }

  async answer(contractId: string, message: string, user: AuthUser) {
    await ensureContractAccess(contractId, user);
    await db
      .insert(chatMessages)
      .values({ contractId, userId: user.id, role: "user", content: message });
    const embedding = await aiClient.embed(message);
    const distance = sql<number>`${clauses.embedding} <=> ${toPgVector(embedding)}::vector`;
    const relevant = await db
      .select({ clauses, distance })
      .from(clauses)
      .innerJoin(contracts, eq(clauses.contractId, contracts.id))
      .where(and(eq(clauses.contractId, contractId), eq(contracts.orgId, user.orgId)))
      .orderBy(distance, desc(clauses.confidenceScore))
      .limit(8);
    const result = await answerScenarioQuestion(aiClient, {
      clauses: relevant.map((row) => row.clauses as never),
      question: message,
      model: defaultModel(),
    });
    await recordAiUsage({
      userId: user.id,
      orgId: user.orgId,
      contractId,
      jobType: "chat",
      model: defaultModel(),
      tokensUsed: result.tokensUsed,
      cost: result.cost,
    });
    await db.insert(chatMessages).values({
      contractId,
      userId: user.id,
      role: "assistant",
      content: result.content,
      relevantClauseIds: relevant.map((row) => row.clauses.id),
      confidenceScore: 0.78,
    });
    return {
      answer: result.content,
      relevantClauses: relevant.map((row) => row.clauses),
      confidence: 0.78,
      disclaimer: "This is legal information generated by AI, not legal advice.",
    };
  }
}

export const chatService = new ChatService();

async function ensureContractAccess(contractId: string, user: AuthUser) {
  const [contract] = await db
    .select({ id: contracts.id })
    .from(contracts)
    .where(
      tenantContractFilter({ userId: user.id, orgId: user.orgId, role: user.role }, contractId),
    )
    .limit(1);
  if (!contract) {
    throw new HTTPException(404, { message: "Contract not found" });
  }
}
