import { answerScenarioQuestion } from "@lexguard/ai";
import { chatMessages, clauses, contracts } from "@lexguard/db";
import { and, asc, eq } from "drizzle-orm";
import { db } from "../lib/db";
import type { AuthUser } from "../middleware/auth";
import { aiClient, defaultModel, recordAiUsage } from "./ai.service";

export class ChatService {
  async history(contractId: string, user: AuthUser) {
    return db
      .select()
      .from(chatMessages)
      .innerJoin(contracts, eq(chatMessages.contractId, contracts.id))
      .where(and(eq(chatMessages.contractId, contractId), eq(contracts.orgId, user.orgId)))
      .orderBy(asc(chatMessages.createdAt));
  }

  async clear(contractId: string, user: AuthUser) {
    await db
      .delete(chatMessages)
      .where(and(eq(chatMessages.contractId, contractId), eq(chatMessages.userId, user.id)));
    return { ok: true };
  }

  async answer(contractId: string, message: string, user: AuthUser) {
    await db
      .insert(chatMessages)
      .values({ contractId, userId: user.id, role: "user", content: message });
    const relevant = await db
      .select()
      .from(clauses)
      .innerJoin(contracts, eq(clauses.contractId, contracts.id))
      .where(and(eq(clauses.contractId, contractId), eq(contracts.orgId, user.orgId)))
      .limit(8);
    const result = await answerScenarioQuestion(aiClient, {
      clauses: relevant.map((row) => row.clauses as never),
      question: message,
      model: defaultModel(),
    });
    await recordAiUsage({
      userId: user.id,
      orgId: user.orgId,
      contractId,
      jobType: "chat",
      model: defaultModel(),
      tokensUsed: result.tokensUsed,
      cost: result.cost,
    });
    await db.insert(chatMessages).values({
      contractId,
      userId: user.id,
      role: "assistant",
      content: result.content,
      relevantClauseIds: relevant.map((row) => row.clauses.id),
      confidenceScore: 0.78,
    });
    return {
      answer: result.content,
      relevantClauses: relevant.map((row) => row.clauses),
      confidence: 0.78,
      disclaimer: "This is legal information generated by AI, not legal advice.",
    };
  }
}

export const chatService = new ChatService();
